spring:
  mvc:
    pathmatch:
      # 适配Swagger-UI和SpringBoot2.7.0以上版本
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    # todo: 项目启动前进行数据库密码修改
    password: password
    url: jdbc:mysql://localhost:3306/wallet_demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
# MyBatis配置
logging:
  level:
    cc.sika.wallet.mapper.*: debug
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cc.sika.order.po
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml